//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionBibliothèque
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int ID_Con { get; set; }
        public string Login { get; set; }
        public string Mot_de_passe { get; set; }
        public string Role { get; set; }
    }
}
