//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionBibliothèque
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecteur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lecteur()
        {
            this.Emprunt = new HashSet<Emprunt>();
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int ID_Lecteur { get; set; }
        public string Code_Lecteur { get; set; }
        public string Nom { get; set; }
        public string Adresse { get; set; }
        public int Id_Biblio { get; set; }
    
        public virtual Bibliotheque Bibliotheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emprunt> Emprunt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
