//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exemplaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exemplaire()
        {
            this.Emprunt = new HashSet<Emprunt>();
        }
    
        public int ID_Exemp { get; set; }
        public string Code_Exemp { get; set; }
        public bool Emprunte { get; set; }
        public Nullable<System.DateTime> Date_Achat { get; set; }
        public int Id_Biblio { get; set; }
        public int Id_Livre { get; set; }
    
        public virtual Bibliotheque Bibliotheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emprunt> Emprunt { get; set; }
        public virtual Livre Livre { get; set; }
    }
}
