//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public System.DateTime Date_Reserv { get; set; }
        public int Id_Lecteur { get; set; }
        public int Id_Livre { get; set; }
    
        public virtual Lecteur Lecteur { get; set; }
        public virtual Livre Livre { get; set; }
    }
}
