//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarif
    {
        public int ID_Tarif { get; set; }
        public decimal Prix_Inscription { get; set; }
        public decimal Prix_Emprunt { get; set; }
        public decimal Prix_Retard { get; set; }
        public decimal Prix_Academique { get; set; }
        public int Id_Biblio { get; set; }
    
        public virtual Bibliotheque Bibliotheque { get; set; }
    }
}
